### ISSUE TITLE
Can I make it run on GKE (no RBAC) ?

### ISSUE THREAD

**Issue by kilianc** [nicolai86/github-rebase-bot#35]
Thanks so much for this. Fits our stack perfectly and it works exactly as I always wanted.

The problem is GKE and no RBAC. Can I get around not having RBAC enabled in GKE?

**Comment by nicolai86** [comment]
@kilianc these steps should work when RBAC is disabled:

1. update the `deployment.yml` to not reference a service account: `serviceAccountName: rebase-robot` needs to be removed
2. remove `rbac.yml`
3. `kubectl apply -f k8s`

that being said I have not used the rebase bot without RBAC. Let me know if you run into any issues!

**Comment by kilianc** [comment]
it works perfectly just removing the right bits, `kubectl` pretty much tells you what to do

**Comment by nicolai86** [comment]
Thanks for the feedback, @kilianc
